CREATE TABLE MEMBER2(
	MEMBER_ID	VARCHAR2(15),
	MEMBER_PW	VARCHAR2(13),
	MEMBER_NAME	VARCHAR2(15),
	MEMBER_AGE	NUMBER,
	MEMBER_GENDER	VARCHAR2(5),
	MEMBER_EMAIL	VARCHAR2(30),
	PRIMARY KEY(MEMBER_ID)
);
CREATE TABLE MEMBER2_BOARD(
	BOARD_NUM	NUMBER,
	BOARD_ID	VARCHAR2(20),
	BOARD_SUBJECT	VARCHAR2(50),
	BOARD_CONTENT	VARCHAR2(2000),
	BOARD_FILE	VARCHAR2(50),
	BOARD_RE_REF	NUMBER,
	BOARD_RE_LEV	NUMBER,
	BOARD_RE_SEQ	NUMBER,
	BOARD_READCOUNT	NUMBER,
	BOARD_DATE	DATE,
	PRIMARY KEY(BOARD_NUM)
);
----------------------------------------------------------
ALTER TABLE MEMBER2_BOARD
ADD CONSTRAINT pk_board_id FOREIGN KEY(board_id) REFERENCES member2(member_id);

insert into MEMBER2 (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_AGE,MEMBER_GENDER,MEMBER_EMAIL) values ('admin','admin','È«±æµ¿',20,'³²','admin@email.com');